name: icilome_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.2
  http: ^0.12.0+2
  html: ^0.14.0+3
  flutter_html: ^0.11.0
  dio: ^3.0.6
  loading: ^1.0.2
  intl: ^0.16.0
  share: ^0.6.3+3
  path_provider: ^1.4.5
  sqflite: ^1.1.7+3
  flutter_widget_from_html: ^0.2.4+4

  firebase_core: ^0.4.2+1
  firebase_messaging: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/play-button.png
    - assets/boxed/A-ne-pas-manquer.png
    - assets/boxed/buzz.png
    - assets/boxed/conseil-des-ministres.png
    - assets/boxed/economie.png
    - assets/boxed/English.png
    - assets/boxed/faits-divers.png
    - assets/boxed/opinion.png
    - assets/boxed/politic.png
    - assets/boxed/revue-de-presse.png
    - assets/boxed/sante.png
    - assets/boxed/sport.png
    - assets/boxed/benin.png
    - assets/boxed/society.png
    - assets/boxed/international.png
    - assets/boxed/diplomatie.png
    - assets/more/favourite.png
    - assets/more/contact.png
    - assets/more/share.png
    

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
  
    - family: Soleil
      fonts:
        - asset: fonts/Soleil/Soleil-Bold-italic.otf
        - asset: fonts/Soleil/Soleil-Bold.otf
        - asset: fonts/Soleil/Soleil-ExtraBold-italic.otf
        - asset: fonts/Soleil/Soleil-ExtraBold.otf
        - asset: fonts/Soleil/Soleil-italic.otf
        - asset: fonts/Soleil/Soleil-Light-italic.otf
        - asset: fonts/Soleil/Soleil-Light.otf
        - asset: fonts/Soleil/Soleil-Regular.otf
        - asset: fonts/Soleil/Soleil-SemiBold-italic.otf
        - asset: fonts/Soleil/Soleil-SemiBold.otf